"""fix in datetime

Revision ID: ed2ca4b8b10b
Revises: 55018beab2be
Create Date: 2026-05-23 16:32:42.145342

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed2ca4b8b10b'
down_revision: Union[str, Sequence[str], None] = '55018beab2be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('updated_at', sa.DateTime(), server_default=sa.text("timezone('UTC', CURRENT_TIMESTAMP)"), nullable=False))
    op.alter_column('user', 'created_at',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               nullable=False)
    op.drop_column('user', 'update_at')
    # ### end Alembic commands ###
    op.alter_column(
        "user",
        "created_at",
        server_default=sa.text(
            "timezone('UTC', CURRENT_TIMESTAMP)"
        ),
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('update_at', sa.DATE(), autoincrement=False, nullable=True))
    op.alter_column('user', 'created_at',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               nullable=True)
    op.drop_column('user', 'updated_at')
    # ### end Alembic commands ###
    op.alter_column(
        "user",
        "created_at",
        server_default=None,
    )
